
USE DATABASE IMT577_DW_ASAD_HUSSAIN_M5

create or replace file format CSV_SKIP_HEADER
type = 'csv'
field_delimiter = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
skip_header = 1;

TRUNCATE STAGE_CHANNEL;

SELECT * FROM Stage_Channel


CREATE TABLE "IMT577_DW_ASAD_HUSSAIN_M5"."PUBLIC"."STAGE_CHANNELCATEGORY"
("CHANNELCATEGORYID" INTEGER NOT NULL, "CHANNELCATEGORY" VARCHAR(250) NOT NULL, "CREATEDDATE" DATE NOT NULL, "CREATEDBY" VARCHAR (250) NOT NULL, "MODIFIEDDATE" DATE, "MODIFIEDBY" VARCHAR (250));

CREATE TABLE "IMT577_DW_ASAD_HUSSAIN_M5"."PUBLIC"."STAGE_CUSTOMER" 
("CUSTOMERID" VARCHAR(250) NOT NULL, "SUBSEGMENT" INTEGER NOT NULL, "FIRSTNAME" VARCHAR (250) NOT NULL,"LASTNAME" VARCHAR (250) NOT NULL, "GENDER" VARCHAR (20) NOT NULL, "EMAILADDRESS" VARCHAR (250) NOT NULL, 
 "ADDRESS" VARCHAR (250) NOT NULL, "CITY" VARCHAR (250) NOT NULL, "STATEPROVINCE" VARCHAR (250) NOT NULL, "COUNTRY" VARCHAR (250) NOT NULL, "POSTALCODE" VARCHAR (50) NOT NULL, "PHONENUMBER" VARCHAR (250) NOT NULL,
 "CREATEDDATE" DATE NOT NULL, "CREATEDBY" VARCHAR (250) NOT NULL, "MODIFIEDDATE" DATE, "MODIFIEDBY" VARCHAR (250));
 
 CREATE TABLE "IMT577_DW_ASAD_HUSSAIN_M5"."PUBLIC"."STAGE_PRODUCT" 
("PRODUCTID" INTEGER NOT NULL, "PRODUCTTYPE" INTEGER NOT NULL, "PRODUCT" VARCHAR (250) NOT NULL,"COLOR" VARCHAR (250), "STYLE" VARCHAR (20), "UNITOFMEASURE" INTEGER NOT NULL, 
 "WEIGHT" INTEGER NOT NULL, "PRICE" INTEGER NOT NULL, "COST" INTEGER NOT NULL,
 "CREATEDDATE" DATE NOT NULL, "CREATEDBY" VARCHAR (250) NOT NULL, "MODIFIEDDATE" DATE, "MODIFIEDBY" VARCHAR (250), "WHOLESALEPRICE" VARCHAR (250) NOT NULL);
 
 CREATE TABLE "IMT577_DW_ASAD_HUSSAIN_M5"."PUBLIC"."STAGE_PRODUCTCATEGORY"
("PRODUCTCATEGORYID" INTEGER NOT NULL, "PRODUCTCATEGORY" VARCHAR(250) NOT NULL, "CREATEDDATE" DATE NOT NULL, "CREATEDBY" VARCHAR (250) NOT NULL, "MODIFIEDDATE" DATE, "MODIFIEDBY" VARCHAR (250));

CREATE TABLE "IMT577_DW_ASAD_HUSSAIN_M5"."PUBLIC"."STAGE_PRODUCTTYPE"
("PRODUCTTYPEID" INTEGER NOT NULL, "PRODUCTCATEGORY" VARCHAR(250) NOT NULL, "PRODUCTTYPE" VARCHAR(250) NOT NULL, "CREATEDDATE" DATE NOT NULL, "CREATEDBY" VARCHAR (250) NOT NULL, "MODIFIEDDATE" DATE, "MODIFIEDBY" VARCHAR (250));

CREATE TABLE "IMT577_DW_ASAD_HUSSAIN_M5"."PUBLIC"."STAGE_RESELLER" 
("RESELLERID" VARCHAR(250) NOT NULL, "CONTACT" VARCHAR (250) NOT NULL, "EMAILADDRESS" VARCHAR (250) NOT NULL, 
 "ADDRESS" VARCHAR (250) NOT NULL, "CITY" VARCHAR (250) NOT NULL, "STATEPROVINCE" VARCHAR (250) NOT NULL, "COUNTRY" VARCHAR (250) NOT NULL, "POSTALCODE" VARCHAR (50) NOT NULL, "PHONENUMBER" VARCHAR (250) NOT NULL,
 "CREATEDDATE" DATE NOT NULL, "CREATEDBY" VARCHAR (250) NOT NULL, "MODIFIEDDATE" DATE, "MODIFIEDBY" VARCHAR (250), "RESELLERNAME" VARCHAR(250) NOT NULL);

CREATE TABLE "IMT577_DW_ASAD_HUSSAIN_M5"."PUBLIC"."STAGE_SALESDETAIL"
("SALESDETAILID" INTEGER NOT NULL, "SALESHEADERID" INT NOT NULL, "PRODUCTID" INT NOT NULL, "SALESQUANTITY" VARCHAR(250), "SALESAMOUNT" VARCHAR(250),
 "CREATEDDATE" DATE NOT NULL, "CREATEDBY" VARCHAR (250) NOT NULL, "MODIFIEDDATE" DATE, "MODIFIEDBY" VARCHAR (250));

CREATE TABLE "IMT577_DW_ASAD_HUSSAIN_M5"."PUBLIC"."STAGE_SALESHEADER"
("SALESHEADERID" INTEGER NOT NULL, "DATE" DATE NOT NULL, "CHANNELID" INT NOT NULL, "STOREID" INT, "CUSTOMERID" VARCHAR(250),"RESELLERID" VARCHAR(250),
 "CREATEDDATE" DATE NOT NULL, "CREATEDBY" VARCHAR (250) NOT NULL, "MODIFIEDDATE" DATE, "MODIFIEDBY" VARCHAR (250));

CREATE TABLE "IMT577_DW_ASAD_HUSSAIN_M5"."PUBLIC"."STAGE_STORE" 
("STOREID" INTEGER NOT NULL, "SUBSEGMENTID" INTEGER NOT NULL, "STORENUMBER" INTEGER NOT NULL, "STOREMANAGER" VARCHAR (250),
 "ADDRESS" VARCHAR (250) NOT NULL, "CITY" VARCHAR (250) NOT NULL, "STATEPROVINCE" VARCHAR (250) NOT NULL, "COUNTRY" VARCHAR (250) NOT NULL, "POSTALCODE" VARCHAR (50) NOT NULL, "PHONENUMBER" VARCHAR (250) NOT NULL,
 "CREATEDDATE" DATE NOT NULL, "CREATEDBY" VARCHAR (250) NOT NULL, "MODIFIEDDATE" DATE, "MODIFIEDBY" VARCHAR (250));

CREATE TABLE "IMT577_DW_ASAD_HUSSAIN_M5"."PUBLIC"."STAGE_TARGETDATACHANNELRESELLERSTORE"
("YEAR" DATE NOT NULL, "CHANNELNAME" VARCHAR(250) NOT NULL, "TARGETNAME" VARCHAR(250) NOT NULL, "TARGETSALESAMOUNT" INTEGER);

CREATE TABLE "IMT577_DW_ASAD_HUSSAIN_M5"."PUBLIC"."STAGE_TARGETDATAPRODUCT"
("PRODUCTID" INTEGER NOT NULL, "PRODUCT" VARCHAR(250) NOT NULL, "YEAR" DATE NOT NULL, "SALESQUANTITYTARGET" INTEGER);

TRUNCATE TABLE IF EXISTS STAGE_CHANNEL;
TRUNCATE TABLE IF EXISTS STAGE_CHANNELCATEGORY;
TRUNCATE TABLE IF EXISTS STAGE_CUSTOMER;
TRUNCATE TABLE IF EXISTS STAGE_PRODUCT;
TRUNCATE TABLE IF EXISTS STAGE_PRODUCTCATEGORY;
TRUNCATE TABLE IF EXISTS STAGE_PRODUCTTYPE;
TRUNCATE TABLE IF EXISTS STAGE_RESELLER;
TRUNCATE TABLE IF EXISTS STAGE_SALESDETAIL;
TRUNCATE TABLE IF EXISTS STAGE_SALESHEAFER;
TRUNCATE TABLE IF EXISTS STAGE_STORE;
TRUNCATE TABLE IF EXISTS STAGE_TARGETDATACHANNELRESELLERSTORE;
TRUNCATE TABLE IF EXISTS STAGE_TARGETDATAPRODUCT;

SELECT * FROM STAGE_CHANNEL

